name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: nashitakalila
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run containers
        run: |
          docker-compose up -d --build

      - name: Wait for the server to be ready
        run: |
          until curl -s http://127.0.0.1:5000 > /dev/null; do
            echo "Waiting for the server to be ready..."
            sleep 5
          done
          echo "Server is up and running!"

      - name: Run tests
        run: |
          curl http://127.0.0.1:5000

      - name: Tear down
        run: docker-compose down

  deploy_streamlit:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Streamlit app
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: app.py
