name: Streamlit CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Gantikan dengan nama file requirements Anda

      - name: Run Streamlit app
        run: |
          streamlit run app.py &> streamlit.log &
          echo "Streamlit app is starting..."

      - name: Wait for Streamlit to be ready
        run: |
          until curl -s http://localhost:5000 > /dev/null; do
            echo "Waiting for Streamlit app to be ready..."
            sleep 5
          done
          echo "Streamlit app is up and running!"

      - name: Run tests
        run: |
          curl http://localhost:5000  # Gantikan dengan uji tes yang sesuai untuk aplikasi Streamlit Anda

      - name: Tear down
        run: |
          kill $(pidof streamlit)
